version: '3'

services:
 app:
  depends_on: 
   - redis
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8000:8000"
  expose:
   - "8000"
  volumes:
   - .:/app
  networks:
   - quiz_app_net
  command: sh -c "pipenv run python ./project_quiz/manage.py makemigrations &&
   pipenv run python ./project_quiz/manage.py migrate &&
   pipenv run python ./project_quiz/manage.py init_admin &&
   pipenv run python ./project_quiz/manage.py runserver 0.0.0.0:8000"

 
 redis:
  image: redis:alpine
  networks:
   - quiz_app_net
  
networks:
 quiz_app_net:
  driver: bridge